### ISSUE TITLE
Resistor pack array question

### ISSUE THREAD

**Issue by rapiqui** [revaldinho/cpc_ram_expansion#10]
Hi,

Could you please specify which is the value of the resistor pack array and the type (f.ex.: 9 pin + gnd).

I've been unable to figure it out.

Thanks!

**Comment by revaldinho** [comment]
Thank you for your question.

Several of the projects in this repository use resistor packs. Which one are you building ?

R

**Comment by rapiqui** [comment]
Hi @revaldinho,

Thanks for your swift reply.
It's the Amstrad Universal RAM Expansion 512k.

**Comment by revaldinho** [comment]
For these two components, see the [PCB netlist](https://github.com/revaldinho/cpc_ram_expansion/blob/master/cpc_ram_expansion/pcb/cpc_ram512k_v110.v).

  **r6k8_sil5   sil0 (**
                    .common(VSS),
                    .p0(dip0),
                    .p1(dip1),
                    .p2(HIADR3),
                    .p3(HIADR4),
                    );
  **r3k3_sil5   sil1 (**
                    .common(VDD),
                    .p0(dip3_pu),
                    .p1(dip2_pu),
                    .p2(dip1_pu),
                    .p3(dip0_pu),
                    );

The first is a 6K8 pack and the second a 3K3. I didn't find any 5 pin arrays for the 6K8 when I ordered from Digi-Key so I used a 6 pin one and snipped off the last array leg. No problem finding 5 pin packs for the 3K3.

**Comment by rapiqui** [comment]
Thanks,

Now is crystal clear ;)

**Comment by revaldinho** [comment]
You're welcome. I'll close the issue now.

thanks

R
