### ISSUE TITLE
Pin1/2 silkscreen is on the wrong end of the connector

### ISSUE THREAD

**Issue by SerErris** [revaldinho/cpc_ram_expansion#11]
Hi, I doublechecked now the design on the original here and it is the same as in my version I have (which is modified design by cpcstore.uk.co ... 

The issue is .. if you looking on the board from top, the connector to CPC facing away from you, you can read the PIN numbering of the IDC connectors (1 and 2) on the left of the connector. 

Actually Pin 1 and 2 are on the right side and the rows are exchanged. 

Correct orientation would be as shown in the picture below. That is true for the edge connector version as well as for the V1.10 backplane
![image](https://user-images.githubusercontent.com/30804693/156616770-e8e09f02-fdc9-4aac-b520-f9ebf55ed9c6.png)

**Comment by revaldinho** [comment]
The pin numbering shown on the silk screen for the box connectors is part of the library component data for that part. It does not correspond to the PIN numbers used on the edge connector of the CPC.

**Comment by hanshuebner** [comment]
I was also confused by this, thank you for confirming.
