### ISSUE TITLE
DIP switches in v1.01 brd.

### ISSUE THREAD

**Issue by perencia** [revaldinho/cpc_ram_expansion#6]
I don't see the pads for the dip switchers on the 1.01 revision brd file...

**Comment by revaldinho** [comment]
There are no DIP switches on the V1.01 revision of the RAM card. These were added on the V1.10 board. All the source for the V1.10 cards is present but I hadn't checked in the final Eagle board files (which are generated from an Eagle script which itself is generated by running the .v and .footer files through the netlister.py program).  I've added the zip file to the eagle releases area now.

**Comment by perencia** [comment]
Thanks!
