### ISSUE TITLE
cpc_backplane_edge status

### ISSUE THREAD

**Issue by nicf82** [revaldinho/cpc_ram_expansion#8]
Hi

Is the status of the cpc_backplane_edge still correct, I'm taking it that the board has been designed and ordered but not tested?

Id like to order some and try building one but is now a good time to do it? Alternatively are there any distributors creating these yet?

Cheers
Nic

**Comment by revaldinho** [comment]
Hi  Nic

Thanks for the mail and the reminder to update the docs.

In fact I got the boards only last week as they took a bit longer than normal to get back from China via Hong Kong. I built a couple of them up for testing and they work fine with my DDI-3 on the edge connector at the back and other slots full of various other project cards.  I’ll update the wiki shortly.

If you want to build one, you can get bare boards from Seeed directly, where a pack of 10 will cost about £15 including postage. This is the link to my [project gallery](https://www.seeedstudio.com/gallery-user.html?id=292951&user=richarde)

Use the same BOM from DigiKey as the other 4 slot card to identify the components you need and skip the one unlatched box connector.

I don’t think they’ve appeared from any eBay sellers yet, but if you want one already built up then I can provide one. If you PM me via the [cpcwiki forum](http://www.cpcwiki.eu/forum/) or email me directly via GitHub I'll send you a list of prices and payment details.

Rich.
